CREATE TABLE `amp` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `cad` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `cas` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `mim` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `cec` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `chm` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `cod` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `cbd` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `cds` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `cs` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `dsr` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ctq` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ent` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `jso` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `mzp` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `job` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `lca` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `mnm` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `nfs` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `nrm` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `qui` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `ptb` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `rty` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `rwr` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `rso` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `skb` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `wws` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `dbg` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;






/////////////////////////////////////////////////////////
CREATE TABLE `webpulse` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `soccer` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `aquabotix` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `logicleague` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `mini` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;