CREATE TABLE `anti` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `band` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `bizwiz` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `brain` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `cheme` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `mania` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `cod` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `codebid` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `sense` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `counter` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `designer` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `f1race` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `fifa` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `general` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `hydraulic` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `job` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `karyaneeti` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `lca` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `nfs` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `nirmaan` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;


CREATE TABLE `paperp` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `petbottle` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `roboterry` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `war` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `setu` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `snakobot` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `startup` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `technical` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `webpulse` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `soccer` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `aquabotix` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `logicleague` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;

CREATE TABLE `mini` (
	`name` CHAR(50) NULL DEFAULT NULL,
	`email` VARCHAR(50) NULL DEFAULT NULL,
	`age` CHAR(50) NULL DEFAULT NULL,
	`number` VARCHAR(50) NULL DEFAULT NULL,
	`college` VARCHAR(50) NULL DEFAULT NULL,
	`branch` VARCHAR(50) NULL DEFAULT NULL
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;